<a href="https://colab.research.google.com/github/Satyajit99p/DL_Intro_ANN/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import os
os.getcwd()

'/content'

In [3]:
!ls

drive  sample_data


In [4]:
os.chdir('/content/drive/My Drive/ANN')

In [5]:
os.getcwd()

'/content/drive/My Drive/ANN'

In [6]:
import pandas as pd
dataset=pd.read_csv("Copy of Churn_Modelling.csv")

In [7]:
dataset.shape

(10000, 14)

In [8]:
dataset.head()


RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
features=dataset.iloc[:,3:13].values
labels=dataset.iloc[:,13].values

In [11]:
features.shape

(10000, 10)

In [12]:
labels.shape

(10000,)

In [13]:
type(features)
type(labels)

numpy.ndarray

In [14]:
features[0,:]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [15]:
dataset.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [16]:
dataset['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

columnTransformer=ColumnTransformer([('encoder',OneHotEncoder(),[1,2])], remainder='passthrough')

features=np.array(columnTransformer.fit_transform(features), dtype=np.float32)

In [22]:
features[0]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 6.1900000e+02, 4.2000000e+01, 2.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
       1.0134888e+05], dtype=float32)

In [23]:
features=features[:,1:]

In [24]:
features=features[:,[0,1,3,4,5,6,7,8,9,10,11]]

In [25]:
features.shape

(10000, 11)

In [26]:
from sklearn.model_selection import train_test_split
features_train,features_test,labels_train,labels_test=train_test_split(features,labels,test_size=0.25)

In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

features_train=sc.fit_transform(features_train)
features_test=sc.transform(features_test)

In [31]:
import keras
from keras.models import Sequential
from keras.layers import Dense



In [32]:
classifier=Sequential()

In [33]:
features.shape

(10000, 11)

In [34]:
# 1st hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform',activation='relu',input_dim=11))

In [35]:
# 2nd hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

In [36]:
# output layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [37]:
# compiling layer
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [38]:
classifier.fit(features_train, labels_train, batch_size=10, epochs=10)

Epoch 1/10
750/750 [==============================] - 1s 894us/step - loss: 0.4784 - accuracy: 0.7981
Epoch 2/10
750/750 [==============================] - 1s 898us/step - loss: 0.4262 - accuracy: 0.7981
Epoch 3/10
750/750 [==============================] - 1s 923us/step - loss: 0.4225 - accuracy: 0.7981
Epoch 4/10
750/750 [==============================] - 1s 899us/step - loss: 0.4176 - accuracy: 0.8112
Epoch 5/10
750/750 [==============================] - 1s 927us/step - loss: 0.4143 - accuracy: 0.8244
Epoch 6/10
750/750 [==============================] - 1s 891us/step - loss: 0.4120 - accuracy: 0.8297
Epoch 7/10
750/750 [==============================] - 1s 891us/step - loss: 0.4096 - accuracy: 0.8325
Epoch 8/10
750/750 [==============================] - 1s 887us/step - loss: 0.4088 - accuracy: 0.8349
Epoch 9/10
750/750 [==============================] - 1s 907us/step - loss: 0.4075 - accuracy: 0.8357
Epoch 10/10
750/750 [==============================] - 1s 911us/step - loss: 0.406

In [39]:
labels_pred=classifier.predict_classes(features_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [40]:
labels_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [41]:
len(labels_pred)

2500

In [42]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(labels_test,labels_pred)

In [43]:
cm

array([[1937,   40],
       [ 400,  123]])